export const productsList = [
  {
    id: 1,
    itemName: "Basic Crew Neck Tee",
    img: "/item1.png",
    color: "Black",
    price: "$44.00",
    amount: 1,
    new: true,
    discount: true,
    discountAmout: "10%",
  },
  {
    id: 2,
    itemName: "Basic Crew Neck Tee",
    img: "/item2.png",
    color: "Black",
    price: "$44.00",
    amount: 1,
    new: true,
    discount: false,
    discountAmout: "10%",
  },
  {
    id: 3,
    itemName: "Basic Crew Neck Tee",
    img: "/item3.png",
    color: "Black",
    price: "$44.00",
    amount: 1,
    new: true,
    discount: true,
    discountAmout: "10%",
  },
  {
    id: 4,
    itemName: "Basic Crew Neck Tee",
    img: "/item4.png",
    color: "Black",
    price: "$44.00",
    amount: 1,
    new: false,
    discount: false,
    discountAmout: "10%",
  },
  {
    id: 5,
    itemName: "Basic Crew Neck Tee",
    img: "/item5.png",
    color: "Black",
    price: "$44.00",
    amount: 1,
    new: true,
    discount: false,
    discountAmout: "10%",
  },
  {
    id: 6,
    itemName: "Basic Crew Neck Tee",
    img: "/item6.png",
    color: "Black",
    price: "$44.00",
    amount: 1,
    new: false,
    discount: true,
    discountAmout: "10%",
  },
  {
    id: 7,
    itemName: "Basic Crew Neck Tee",
    img: "/item7.png",
    color: "Black",
    price: "$44.00",
    amount: 1,
    new: true,
    discount: true,
    discountAmout: "10%",
  },
  {
    id: 8,
    itemName: "Basic Crew Neck Tee",
    img: "/item8.png",
    color: "Black",
    price: "$44.00",
    amount: 1,
    new: true,
    discount: true,
    discountAmout: "10%",
  },
  {
    id: 9,
    itemName: "Basic Crew Neck Tee",
    img: "/item9.png",
    color: "Black",
    price: "$44.00",
    amount: 1,
    new: true,
    discount: false,
    discountAmout: "10%",
  },
  {
    id: 10,
    itemName: "Basic Crew Neck Tee",
    img: "/item10.png",
    color: "Black",
    price: "$44.00",
    amount: 1,
    new: false,
    discount: false,
    discountAmout: "10%",
  },
];
